spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  profiles:
    include:
    - oauth
    - dbconn
    - s3
    - security
  application:
    name: api

  jpa:
    hibernate:
      ddl-auto: update # 배포할땐 이렇게하면 망할수 있으니 조심 (배포할때 끄기)
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true # SQL 로그 출력
    database-platform: org.hibernate.dialect.MariaDBDialect



  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      - src/main/resources
      additional-exclude: static/**
    livereload:
      enabled: true
      
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security.oauth2: INFO # 디버그 레벨을 낮춤